<a href="https://colab.research.google.com/github/pyrozhenko/Pyrozhenko-Ivan/blob/master/%D0%9F%D0%B8%D1%80%D0%BE%D0%B6%D0%B5%D0%BD%D0%BA%D0%BE%20%D0%86%D0%B2%D0%B0%D0%BD%20%D0%A4%D0%86%D0%A2%203-4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Пироженко Іван Варіант 21

In [7]:
#1 завдання Пироженко Іван Варіант 21
import numpy as np

# Створюємо вектор із зворотніми значеннями натуральних чисел, починаючи з 1
n = 10  # Кількість елементів у векторі (за бажанням можна змінити)
natural_numbers = np.arange(1, n + 1)
inverse_vector = 1 / natural_numbers

# Виводимо вектор з оберненими значеннями
print("Вектор з оберненими значеннями натуральних чисел:")
print(inverse_vector)


Вектор з оберненими значеннями натуральних чисел:
[1.         0.5        0.33333333 0.25       0.2        0.16666667
 0.14285714 0.125      0.11111111 0.1       ]


In [6]:
#2
import numpy as np

# Створюємо матрицю 3x3 з косинусами натуральних чисел
n = 3  # Розмірність матриці (3x3)
natural_numbers = np.arange(1, n * n + 1)
cosine_matrix = np.cos(natural_numbers).reshape((n, n))

# Виводимо матрицю з косинусами
print("Матриця з косинусами натуральних чисел:")
print(cosine_matrix)


Матриця з косинусами натуральних чисел:
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [8]:
#3
import numpy as np

# Створюємо масив розміром 7x7 та заповнюємо його випадковими цілими числами від -50 до 50
np.random.seed(0)  # Задаємо seed для відтворюваності результатів
matrix = np.random.randint(-50, 51, size=(7, 7))

# Знаходимо додатні елементи масиву
positive_elements = matrix[matrix > 0]

# Знаходимо непарні елементи серед додатніх елементів
odd_positive_elements = positive_elements[positive_elements % 2 == 1]

# Обчислюємо відсоток непарних чисел серед додатних елементів
percentage_odd_positive = (len(odd_positive_elements) / len(positive_elements)) * 100

# Виводимо результат
print("Масив:")
print(matrix)
print("\nВідсоток непарних чисел серед додатніх елементів: {:.2f}%".format(percentage_odd_positive))


Масив:
[[ -6  -3  14  17  17 -41  33]
 [-29 -14  37  20  38  38 -38]
 [  8  15 -11  37  -4  38  31]
 [-13 -25  27  22 -41 -30  30]
 [ 19  29  -3  14  32  49  38]
 [ -1 -21 -31 -31 -36 -11 -18]
 [ 15 -41   7 -18 -19  24 -27]]

Відсоток непарних чисел серед додатніх елементів: 52.00%


In [9]:
#4
import numpy as np

matrix = np.random.uniform(-0.7, 0.7, size=(4, 4))

print("Масив розміром 4x4 з випадковими дійсними числами:")
print(matrix)


Масив розміром 4x4 з випадковими дійсними числами:
[[-0.32962214  0.38392717 -0.06138953  0.09580753]
 [-0.67369428  0.1646897   0.15693401  0.1637076 ]
 [ 0.62124731  0.25454842 -0.19668894 -0.08815526]
 [ 0.27668367 -0.61568434  0.2334734   0.23889302]]


In [11]:
#5
import numpy as np

# Створюємо два масиви розміром 5 і заповнюємо їх випадковими цілими числами в діапазоні від 10 до 20
array1 = np.random.randint(10, 21, size=5)
array2 = np.random.randint(10, 21, size=5)

# Виконуємо поелементні операції додавання, віднімання та множення
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

# Виводимо результати
print("Перший масив:", array1)
print("Другий масив:", array2)
print("Результат додавання:", addition_result)
print("Результат віднімання:", subtraction_result)
print("Результат множення:", multiplication_result)


Перший масив: [12 10 13 15 19]
Другий масив: [20 14 14 16 14]
Результат додавання: [32 24 27 31 33]
Результат віднімання: [-8 -4 -1 -1  5]
Результат множення: [240 140 182 240 266]


In [10]:
#6 завдання
import numpy as np

vector1 = np.array([1.5, 2.0, 3.7, 4.2, 5.1, 6.3])
vector2 = np.array([0.8, 2.5, 3.2, 5.0, 6.8, 1.9])

scalar_product = np.dot(vector1, vector2)

print(scalar_product)


85.69


In [12]:
#7
import numpy as np

matrix1 = np.random.randint(1, 11, size=(2, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))

result_matrix = np.dot(matrix1, matrix2)

print(result_matrix)


[[ 74  94  58]
 [104  99  68]]


In [13]:
#8
import numpy as np

matrix = np.random.randint(1, 13, size=(2, 2))
inverse_matrix = np.linalg.inv(matrix)

print(matrix)
print("Обернена матриця:")
print(inverse_matrix)

[[1 6]
 [1 2]]
Обернена матриця:
[[-0.5   1.5 ]
 [ 0.25 -0.25]]


In [14]:
#9
import numpy as np

matrix = np.random.uniform(0, 1, size=(3, 3))
transposed_matrix = np.transpose(matrix)

print(matrix)
print("Транспонована матриця:")
print(transposed_matrix)

[[0.83794491 0.09609841 0.97645947]
 [0.4686512  0.97676109 0.60484552]
 [0.73926358 0.03918779 0.28280696]]
Транспонована матриця:
[[0.83794491 0.4686512  0.73926358]
 [0.09609841 0.97676109 0.03918779]
 [0.97645947 0.60484552 0.28280696]]


In [15]:
#10
import numpy as np

# Створюємо матрицю розміром 3x4 і заповнюємо її випадковими цілими числами в діапазоні від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створюємо вектор розміром 4 і заповнюємо його випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, size=4)

# Знаходимо суму добутків елементів кожного рядка матриці на відповідний елемент вектору
result = np.sum(matrix * vector, axis=1)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Результат:")
print(result)

Матриця:
[[ 8  3 10  3]
 [ 4  4  3  4]
 [ 5  2  3 10]]
Вектор:
[0.92115761 0.08311249 0.27771856 0.0093567 ]
Результат:
[10.42385409  4.88766291  5.69873577]


In [16]:
#11
import numpy as np

# Створюємо матрицю розміром 2x3 і заповнюємо її випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(2, 3))

# Створюємо вектор розміром 3 і заповнюємо його випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=3)

# Знаходимо добуток матриці на вектор
result = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Результат добутку матриці на вектор:")
print(result)

Матриця:
[[0.84234208 0.64717414 0.84138612]
 [0.26473016 0.39782075 0.55282148]]
Вектор:
[9 9 3]
Результат добутку матриці на вектор:
[15.92980434  7.62142269]


In [17]:
#12
import numpy as np

matrix1 = np.random.randint(1, 11, size=(6, 6))
sum_of_elements = np.sum(matrix1)

print(sum_of_elements)

216


In [19]:
#13
import numpy as np

matrix1 = np.random.uniform(-2, 2, size=(5, 5))
matrix2 = np.random.uniform(-2, 2, size=(5, 5))

product_of_elements = np.prod(matrix1) * np.prod(matrix2)

print(product_of_elements)

9.86788973154936e-06


In [18]:
#14
import numpy as np

matrix = np.random.uniform(-10, 10, size=(7, 7))
min_element = np.min(matrix)

print(min_element)

-9.76571831629996


In [20]:
#15
import numpy as np

matrix = np.random.uniform(0, 1, size=(7, 7))
column_sums = np.sum(matrix, axis=0)

print(column_sums)

[3.72360449 4.46005694 3.18777343 3.47801056 3.09008593 1.99670706
 4.68854037]
